// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpulkxzebqmihuvyzxmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdWxreHplYnFtaWh1dnl6eG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzMyNDIsImV4cCI6MjA2MDkwOTI0Mn0.ytvwqCQvudrjI_d_ljcr8txz-OpoMylHF4G5NLblnkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);